### ISSUE TITLE
Не создается отчет allure

### ISSUE THREAD

**Issue by Odium-Mundi** [Odium-Mundi/Patterns2.3#1]
Проблема: отчет allure не создается

Шаги воспроизведения: 
1. Сделать клон репо
2. Добавить в build.gradle - `allure {
    autoconfigure = true
    version = '2.13.2'

    useJUnit5 {
        version = '2.13.2'
    }
}`
`dependencies {
    testImplementation 'io.qameta.allure:allure-selenide:2.13.2' }`
3. В тесты добавить: 
`@BeforeAll
    static void setUpAll() {
      SelenideLogger.addListener("allure", new AllureSelenide());
    }

    @AfterAll
    static void tearDownAll() {
      SelenideLogger.removeListener("allure");
    }`
4. Запустить в терминале `gradle allureReport`
5. Запустить `gradle clean test allureReport`
6. Посмотреть отчет в папке Patterns2.3\build\reports\allure-report\index.html

Ожидаемый результат: 
Готовый отчет
Результат фактический: 
404 ошибка, бесконечный loading

**Comment by andrew-pahomov** [comment]
Добрый вечер.       
1. Четвёртый шаг можно не выполнять, он лишний.    
2. В пятом уточните команду `gradlew clean test allurereport`      
3. Шестым шагом запустите команду `gradlew allureserve`
